# Generated by Django 4.2.3 on 2023-07-17 18:55
# type: ignore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"get_latest_by": "created_at", "ordering": ["name"]},
        ),
    ]
